# Generated by Django 3.1 on 2020-08-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appconf', '0001_initial'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目描述')),
                ('deploy_policy', models.CharField(choices=[('Direct', 'Direct')], max_length=255, verbose_name='部署策略')),
                ('version', models.CharField(blank=True, max_length=255, verbose_name='版本信息')),
                ('build_clean', models.BooleanField(default=False, verbose_name='清理构建')),
                ('rsync_delete', models.BooleanField(default=True, verbose_name='同步删除')),
                ('shell', models.CharField(blank=True, max_length=2048, verbose_name='shell')),
                ('shell_position', models.BooleanField(default=False, verbose_name='本地执行')),
                ('status', models.BooleanField(default=False, verbose_name='部署状态')),
                ('deploy_num', models.IntegerField(default=0, verbose_name='部署次数')),
                ('bar_data', models.IntegerField(default=0)),
                ('source_auth', models.BooleanField(default=False, verbose_name='源码认证')),
                ('auth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.authinfo', verbose_name='认证信息')),
                ('job_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appconf.project', verbose_name='项目名')),
                ('serverList', models.ManyToManyField(blank=True, to='cmdb.Host', verbose_name='所在服务器')),
            ],
        ),
    ]
