# Generated by Django 3.1 on 2020-08-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appconf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='分支机构')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='办公地址')),
                ('telephone', models.CharField(blank=True, max_length=25, null=True, verbose_name='联系电话')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.appowner', verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, verbose_name='资源编码')),
                ('name', models.CharField(max_length=255, verbose_name='资源名称')),
                ('spec', models.CharField(max_length=255, verbose_name='资源规格')),
                ('budget', models.CharField(blank=True, max_length=255, null=True, verbose_name='预算金额')),
                ('paid', models.CharField(blank=True, max_length=255, null=True, verbose_name='合同金额')),
                ('contract', models.CharField(blank=True, max_length=255, null=True, verbose_name='合同编号')),
                ('contract_start', models.DateField(blank=True, max_length=255, null=True, verbose_name='合同开始')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='合同结束')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商名')),
                ('service_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='服务电话')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='合同说明')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='所属机构')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.appowner', verbose_name='供应商联系人')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='行政区域')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='办公地址')),
                ('telephone', models.CharField(blank=True, max_length=25, null=True, verbose_name='联系电话')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注信息')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.appowner', verbose_name='负责人')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.region', verbose_name='所属大区'),
        ),
    ]
